version: "3.7"

services:
  web:
    image: bezysoftware/autosats:v0.4.0
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3311:80
    volumes:
      - ${APP_DATA_DIR}/data:/app_data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      Application__Password: "${APP_PASSWORD}"
      Wallet__Type: "lightning"
      Wallet__Lightning__ConnectionType: "lndREST"
      Wallet__Lightning__BaseUri: "https://$LND_IP:$LND_REST_PORT"
      Wallet__Lightning__MacaroonFilePath: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/walletkit.macaroon"
      Wallet__Lightning__CertificatePath: "/lnd/tls.cert"